=head1 NAME

rsbackup-mount - mount encrypted disks used by rsbackup

=head1 SYNOPSIS

B<rsbackup-mount> [OPTIONS] [--] [DEVICES]

=head1 DESCRIPTION

B<rsbackup-mount> mounts and unmounts encrypted partitions used as
backup stores by L<rsbackup(1)>.

=head1 OPTIONS

=over

=item B<--unmount>
=item B<-u>

Unmount devices.
(The default is to mount devices.)

=item B<--dry-run>
=item <-n>

Do nothing, instead print the commands that would be executed.

=item B<--help>

Display usage message.

=back

=head1 CONFIGURATION

Configuration is read from
I</etc/rsbackup/devices>.
This is a shell script fragment.
It should set
B<devices>
to a (space-separated) list of device names and for each device name
I<D>, define
I<D>B<_uuid>
to its UUID.
(Have a look in
I</dev/disk/by-uuid>
to find device UUIDs).

=head1 SEE ALSO

L<rsbackup(1)>, L<rsbackup.cron.1>

=head1 AUTHOR

Richard Kettlewell <rjk@greenend.org.uk>
