=head1 NAME

rsbackup.cron - cron script for rsbackup

=head1 SYNOPSIS

B<rsbackup.cron> [OPTIONS] FREQUENCY

=head1 DESCRIPTION

B<rsbackup.cron> is invoked from cron to run automated backups, pruning
and reporting.

FREQUENCY must be one of B<hourly>, B<daily>, B<weekly> or B<monthly>,
corresponding to the frequency it is invoked at.

=head1 OPTIONS

=over

=item B<--dry-run>

Pass the B<--dry-run> option to B<rsbackup>.

=item B<--verbose>

Display the B<rsbackup> command before executing it.

=item B<--help>

Display a usage message and exit.

=back

=head1 CONFIGURATION

Configuration is read from I</etc/rsbackup/defaults>.  This is a shell
script fragment and it should define the following variables:

=over

=item B<hourly>

=item B<daily>

=item B<weekly>

=item B<monthly>

Define the list of hosts to back up at a given frequency.  Use the
special string B<_all> to back up all hosts.

=item B<report>

Defines the frequency to send an email report.

=item B<email>

Defines the destination address for the email report.

=item B<prune>

Defines the frequency of pruning old backups.

=item B<prune_incomplete>

Defines the frequency of pruning incomplete backups.

=back

=head1 SEE ALSO

L<rsbackup(1)>

=head1 AUTHOR

Richard Kettlewell <rjk@greenend.org.uk>
