#! /bin/bash
# Copyright © 2011, 2012 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e
. ${srcdir:-.}/setup.sh

setup

echo "| --dry-run should do nothing"
RUN=dryrun RSBACKUP_TODAY=1980-01-01 s ${RSBACKUP} --dry-run --backup host1:volume1
absent dryrun-pre.ran
absent dryrun-post.ran
absent store1/host1/volume1/1980-01-01
absent store1/host1/volume2
absent store2/host1

echo "| Create backup for one volume"
RUN=volume1 RSBACKUP_TODAY=1980-01-01 s ${RSBACKUP} --backup host1:volume1
exists volume1-pre.ran
exists volume1-post.ran
compare volume1 store1/host1/volume1/1980-01-01
absent store1/host1/volume2
absent store1/host1/volume3
absent store2/host1/volume2
absent store2/host1/volume3
s ${RSBACKUP} -T -

echo "| Create backup for one host"
RUN=host1 RSBACKUP_TODAY=1980-01-02 s ${RSBACKUP} --backup host1
exists host1-pre.ran
exists host1-post.ran
compare volume1 store1/host1/volume1/1980-01-02
compare volume2 store1/host1/volume2/1980-01-02
absent store1/host1/volume3
compare volume3 store2/host1/volume3/1980-01-02
s ${RSBACKUP} -T -

echo "| Create backup for everything"
RUN=all RSBACKUP_TODAY=1980-01-03 s ${RSBACKUP} --backup 
exists all-pre.ran
exists all-post.ran
compare volume1 store1/host1/volume1/1980-01-03
compare volume2 store1/host1/volume2/1980-01-03
absent store1/host1/volume3
compare volume3 store2/host1/volume3/1980-01-03
s ${RSBACKUP} -T -

cleanup
