#! /bin/sh
# Copyright © 2019 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e
. ${srcdir:-.}/setup.sh

BACKUP_POLICY=interval
BACKUP_INTERVAL=3600
setup

export EXPECT_STATUS=ok

echo "| Create backup"
RUN=volume1 RSBACKUP_TIME=315532800 s ${RSBACKUP} --backup host1:volume1
compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-01T00:00:00

echo "| Another backup in less than an hour"
RUN=volume1 RSBACKUP_TIME=315534600 s ${RSBACKUP} --backup host1:volume1
absent ${WORKSPACE}/store1/host1/volume1/1980-01-01T00:30:00

echo "| Another backup after an hour"
RUN=volume1 RSBACKUP_TIME=315536400 s ${RSBACKUP} --backup host1:volume1
compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-01T01:00:00
