#! /usr/bin/env bash
# Copyright © 2012 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e
. ${srcdir:-.}/setup.sh

setup

echo "| Backup is skipped if check-file missing"
rm -f volume1/file1
RSBACKUP_TODAY=1980-01-03 s ${RSBACKUP} --backup --verbose --text got/19.txt --html got/19.html
absent store1/host1/volume1
compare volume2 store1/host1/volume2/1980-01-03
absent store1/host1/volume3
compare volume3 store2/host1/volume3/1980-01-03
compare ${srcdir:-.}/expect/19.txt got/19.txt
compare ${srcdir:-.}/expect/19.html got/19.html

cleanup
