#! /bin/bash
# Copyright © 2017 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e
. ${srcdir:-.}/setup.sh
RSBACKUP="${VALGRIND} ${PWD}/../src/rsbackup"

rm -rf ${WORKSPACE}
mkdir ${WORKSPACE}

cd ${srcdir}/bad-configs
for config in *.config; do
  if ${RSBACKUP} --config ${config} ${VERBOSE_OPT} \
                 --dump-config >${WORKSPACE}/got.txt 2>${WORKSPACE}/errors.txt;
  then
    echo >&2 "ERROR: parse of ${srcdir}/bad-configs/${config} unexpectedly succeeded"
    exit 1
  else
    errors=${config%%.config}.errors
    compare $errors ${WORKSPACE}/errors.txt
  fi
done
