#! /usr/bin/env bash
# Copyright © 2014 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e
. ${srcdir:-.}/setup.sh
. ${srcdir:-.}/../scripts/fakeshell.sh

setup

fake_init

sed < ${WORKSPACE}/config > ${WORKSPACE}/config.new \
    's/check-file.*/check-mounted/'
mv ${WORKSPACE}/config.new ${WORKSPACE}/config

case $(uname -s) in
Darwin | *BSD )
  stat_opt=-f
  ;;
* )
  stat_opt=-c
  ;;
esac

fake_reset
fake_cmd --must-run stat "echo 99; echo 99" \
         --must-args $stat_opt %d ${WORKSPACE}/store1/host1/volume3 ${WORKSPACE}/store1/host1/volume3/..

echo "| Backup is skipped if check-mounted fails"
rm -f ${WORKSPACE}/volume1/file1
RSBACKUP_TODAY=1980-01-03 s fake_run ${RSBACKUP} --backup --verbose --text ${WORKSPACE}/got/19.txt --html ${WORKSPACE}/got/19.html
absent ${WORKSPACE}/store1/host1/volume1
compare ${WORKSPACE}/volume2 ${WORKSPACE}/store1/host1/volume2/1980-01-03
absent ${WORKSPACE}/store1/host1/volume3
compare ${WORKSPACE}/volume3 ${WORKSPACE}/store2/host1/volume3/1980-01-03
compare ${srcdir:-.}/expect/19.txt ${WORKSPACE}/got/19.txt
compare ${srcdir:-.}/expect/19.html ${WORKSPACE}/got/19.html

fake_reset
fake_cmd --must-run stat "echo 99; echo 66" \
         --must-args $stat_opt %d ${WORKSPACE}/store1/host1/volume3 ${WORKSPACE}/store1/host1/volume3/..

echo "| Backup is made if check-mounted succeeds"
RUN=all RSBACKUP_TODAY=1980-01-03 s fake_run ${RSBACKUP} --backup --text ${WORKSPACE}/got/23.txt --html ${WORKSPACE}/got/23.html
exists ${WORKSPACE}/all-pre.acted
exists ${WORKSPACE}/all-post.acted
compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-03
compare ${WORKSPACE}/volume2 ${WORKSPACE}/store1/host1/volume2/1980-01-03
absent ${WORKSPACE}/store1/host1/volume3
compare ${WORKSPACE}/volume3 ${WORKSPACE}/store2/host1/volume3/1980-01-03
compare ${srcdir:-.}/expect/23.txt ${WORKSPACE}/got/23.txt
compare ${srcdir:-.}/expect/23.html ${WORKSPACE}/got/23.html

cleanup
