#! /bin/sh
# Copyright © 2011, 2012, 2014, 2015, 2018 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e
. ${srcdir:-.}/setup.sh

setup

export EXPECT_STATUS=ok

sed < ${WORKSPACE}/config > ${WORKSPACE}/config.new \
    '/^store /d';
echo "store-pattern --no-mounted ${WORKSPACE}/store*" >>${WORKSPACE}/config.new
mv -f ${WORKSPACE}/config.new ${WORKSPACE}/config

echo "| Create backup for everything using glob-pattern directive"
RUN=all RSBACKUP_TIME=315705600 s ${RSBACKUP} --backup --text ${WORKSPACE}/got/everything.txt --html ${WORKSPACE}/got/everything.html
exists ${WORKSPACE}/all-pre.acted
exists ${WORKSPACE}/all-post.acted
compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-03T00:00:00
compare ${WORKSPACE}/volume2 ${WORKSPACE}/store1/host1/volume2/1980-01-03T00:00:00
absent ${WORKSPACE}/store1/host1/volume3
compare ${WORKSPACE}/volume3 ${WORKSPACE}/store2/host1/volume3/1980-01-03T00:00:00
compare ${srcdir:-.}/expect/glob-store/everything.txt ${WORKSPACE}/got/everything.txt
compare ${srcdir:-.}/expect/glob-store/everything.html ${WORKSPACE}/got/everything.html

cleanup
