#! /bin/bash
# Copyright © 2011 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

set -e

#echo "Running hook..."
#env | grep ^RSBACKUP | sort

case "$RSBACKUP_HOOK" in
pre-backup-hook )
  if [ -e hookdata ]; then
    echo >&2 "ERROR: hookdata already exists"
    exit 1
  fi
  touch hookdata
  [ -z "${RUN}" ] || touch ${RUN}-pre.ran
  ;;
post-backup-hook )
  if [ ! -e hookdata ]; then
    echo >&2 "ERROR: hookdata does not exit"
    exit 1
  fi
  rm -f hookdata
  [ -z "${RUN}" ] || touch ${RUN}-post.ran
  ;;
esac
