#! /bin/sh
# Copyright © 2015 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e
PRUNE_POLICY=exec
MIN_BACKUPS=none
PRUNE_AGE=none
PRUNE_PATH=${srcdir}/pruner.sh
. ${srcdir:-.}/setup.sh

setup

echo "| Create backup"
RSBACKUP_TIME="1980-01-01T00:00:00" s ${RSBACKUP} --backup
echo "| Create second backup"
RSBACKUP_TIME="1980-01-02T00:00:00" s ${RSBACKUP} --backup
echo "| Create third backup"
RSBACKUP_TIME="1980-01-03T00:00:00" s ${RSBACKUP} --backup

compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-01T00:00:00
compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-02T00:00:00
compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-03T00:00:00
compare ${WORKSPACE}/volume2 ${WORKSPACE}/store1/host1/volume2/1980-01-01T00:00:00
compare ${WORKSPACE}/volume2 ${WORKSPACE}/store1/host1/volume2/1980-01-02T00:00:00
compare ${WORKSPACE}/volume2 ${WORKSPACE}/store1/host1/volume2/1980-01-03T00:00:00

echo "| Prune"
RSBACKUP_TIME="1980-01-04T00:00:00" s ${RSBACKUP} --prune

compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-01T00:00:00
absent ${WORKSPACE}/store1/host1/volume1/1980-01-02T00:00:00
compare ${WORKSPACE}/volume1 ${WORKSPACE}/store1/host1/volume1/1980-01-03T00:00:00
compare ${WORKSPACE}/volume2 ${WORKSPACE}/store1/host1/volume2/1980-01-01T00:00:00
absent ${WORKSPACE}/store1/host1/volume2/1980-01-02T00:00:00
compare ${WORKSPACE}/volume2 ${WORKSPACE}/store1/host1/volume2/1980-01-03T00:00:00
sqlite3 ${WORKSPACE}/logs/backups.db "SELECT host,volume,device,id,rc,status,time,pruned,log FROM backup WHERE pruned != 0" > ${WORKSPACE}/got/pruneexec-db.txt
compare ${srcdir}/expect/pruneexec/pruneexec-db.txt ${WORKSPACE}/got/pruneexec-db.txt

cleanup
