#! /bin/bash
# Copyright © 2019 Richard Kettlewell.
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
set -e

echo $(date +%s) start "$RSBACKUP_HOST" "$RSBACKUP_VOLUME" >> ${WORKSPACE}/wrap.log
sleep ${RSYNC_WRAP_DELAY:-0.1}
${RSYNC} "$@"
status=$?
echo $(date +%s) stop "$RSBACKUP_HOST" "$RSBACKUP_VOLUME" >> ${WORKSPACE}/wrap.log
exit $status
