.TH rsbackup 1
.SH NAME
rsbackup \- rsync-based backup utility
.SH SYNOPSIS
\fBrsbackup\fR [\fIOPTIONS\fR] [\fB\-\-\fR] [\fISELECTOR\fR...]
.br
\fBrsbackup \-\-retire [\fIOPTIONS\fR] [\fB\-\-\fR] [\fISELECTOR\fR...]
.br
\fBrsbackup \-\-retire\-device [\fIOPTIONS\fR] [\fB\-\-\fR] \fIDEVICE\fR...
.SH DESCRIPTION
Backs up files from one or more (remote) destinations to a single
backup storage directory, preserving their contents, layout,
ownership, permissions, timestamps and hardlink structure.
.PP
Incremental backups are achieved by hard-linking identical files
within successive backups of the same files.
.SH OPTIONS
.SS "Action Options"
At least one of these options must be specified.
When multiple actions are specified, they are executed in the order
shown below.
.TP
.B \-\-backup\fR, \fB-b
Make a backup of the selected volumes.
At most one backup of a given volume will be made per day.
.TP
.B \-\-retire\-device
Retire the named devices.
Retiring a device means deleting the logfiles for it.
Files on the device itself are not touched.
.IP
If the device is still listed in the configuration file then you will
be asked whether you really want to retire it; you can suppress this
check with the \fB\-\-force\fR option.
.TP
.B \-\-retire
Retire the named hosts and volumes.
Retiring a volume means deleting any available backups for the volume
and their corresponding logfiles.
Logfiles on backups for unavailable devices are not removed.
.IP
If you just want to remove logfiles for retired volumes but want to
keep the backups, you should either manually remove the logfiles, or
rename it within the volume.
.IP
If the volume is still listed in the configuration file then you will
be asked whether you really want to retire it; you can suppress this
check with the \fB\-\-force\fR option.
.TP
.B \-\-prune\fR, \fB\-p
Prune old backups of selected volumes.  Any backups that are older
than the \fBprune\-age\fR listed for them in the current configuration
will be deleted provided that does not reduce the number of backups
below the volume's \fBmin\-backups\fR setting.
.TP
.BR \-\-prune\-incomplete, \fB\-P
Prune incomplete backups of selected volumes.
Any backups that failed before completion will be removed.
.TP
.B \-\-html \fIPATH\fR, \fB\-H \fIPATH
Write an HTML report to \fIPATH\fR.
The report covers all volumes, not just selected ones.
.TP
.B \-\-text \fIPATH\fR, \fB\-T \fIPATH
Write a plain text report to \fIPATH\fR.
The report covers all volumes, not just selected ones.
.TP
.B \-\-email \fIADDRESS\fR, \fB\-e \fIADDRESS
Email a report to \fIADDRESS\fR.
The contents is equivalent to the output of \fB\-\-text\fR and
\fB\-\-html\fR.
.SS "General Options"
.TP
.B \-\-config \fIPATH\fR, \fB\-c \fIPATH
The path to the configuration file.
The default is
.IR /etc/rsbackup/config .
.TP
.B \-\-store \fIPATH\fR, \fB\-s \fIPATH
Specify the destination directory to back up to.
Using this option (possibly more than once) is equivalent to removing
the \fBstore\fR directives from the configuration file and replacing
them with the paths give in \fB\-\-store\fR options.
.IP
This option implicitly enables the \fB\-\-warn\-store\fR option.
.TP
.B \-\-verbose\fR, \fB\-v
Enable verbose mode.
Various messages will be displayed to report progress and the rsync
\fB\-\-quiet\fR option is suppressed.
.TP
.B \-\-dry\-run\fR, \fB\-n
Enable dry-run mode.
Commands will be displayed but nothing will actually be done.
.TP
.B \-\-force\fR, \fB\-f
Suppress checks made when retiring devices and volumes.
.TP
.B \-\-wait\fR, \fB\-w
Waits rather than giving up if another copy of \fBrsbackup\fR is running.
.TP
.B \-\-help\fR, \fB\-h
Display a usage message.
.TP
.B \-\-version\fR, \fB\-V
Display the version number.
.SS "Report Verbosity"
.TP
.B \-\-logs \fIVERBOSITY\fR
Controls which logfiles for a given volume/device pair to include in
the report.
The possible values of \fIVERBOSITY\fR are:
.RS
.TP
.B all
Includes all nonempty logfiles, even if the backup succeeded.
.TP
.B errors
Includes all error logfiles.
.TP
.B recent
Includes only the most recent error logfile.
.TP
.B latest
Includes only the latest logfile, even if the backup succeeded.
.TP
.B failed
Includes only the most recent logfile but only if that attempt failed.
This is the default.
.RE
.SS "Warning Options"
.TP
.B \-\-warn\-unknown
Display warnings for unknown devices, hosts and volumes.
(Warnings will always be included in the report, this refers to
runtime error output.)
.TP
.B \-\-warn\-store
Display warnings for unsuitable store directories and unavailable devices.
.TP
.B \-\-warn\-unreachable
Display warnings for unreachable hosts.
.TP
.B \-\-no\-warn\-partial
Suppress warnings for rsync "partial transfer" diagnostics
(which are on by default).
.TP
.B \-\-warn\-all\fR, \fB\-W
Enable all \fB\-\-warn\-\fR options.
.TP
.B \-\-no\-errors
Suppress display of errors from rsync.
.SS "Volume Selection"
The list of selectors on the command line determines what subset of
the known volumes are backed up, pruned or retired.
The following selectors are possible:
.TP 16
.I HOST
Select all volumes for the host.
.TP
.IR HOST : VOLUME
Select the volume.
.TP
.BI - HOST
Deselect all volumes for the host.
.TP
.BI - HOST : VOLUME
Deselect the volume.
.TP
.B *
Select all volumes.
.PP
If no hosts or volumes are specified on the command line then all volumes are
selected for backing up or pruning.
For retiring, you must explicitly select hosts or volumes to retire
and only positive selections are possible.
.SH "CONFIGURATION FILE"
The config file contains global directives and a series of host
stanzas.
Each host stanze in turn contains host directives and volume stanzas.
Although it is not enforced it is suggested that host and volume
stanzas are indented.
.PP
Comments are introduced by an initial "#".
.PP
Command arguments may be quoted, using "double quotes".
Quotes and backslashes within quoted strings are escaped with
backslashes.
.SS "Global Directives"
.TP
.B store \fIPATH\fR
A path at which a backup device may be mounted.
This can be used multiple times.
.TP
.B device \fIDEVICE\fR
Names a device.
This can be used multiple times.
The store must have a file called \fISTORE\fB/device\-id\fR which
contains a known device name.
Backups will only be
made to known devices.
.IP
When a device is lost or destroyed, remove its device entry and use the
\-\-prune\-unknown option to delete logs of backups on it.
.IP
Device names may contain letters, digits, dots and underscores.
.TP
.B public
Backups are public.
Normally backups must only be accessible by the calling user.
This option suppresses the check.
.TP
.B logs \fIPATH\fR
The directory to store logfiles.
The default is \fI/var/log/backup\fR.
.TP
.B lock \fIPATH\fR
Enable locking.
If this directive is present then \fIPATH\fR will be used as a lockfile
for operations that change anything (\-\-backup, \-\-prune, etc).
.TP
.B ssh\-timeout \fISECONDS\fR
How long to wait before concluding a host is down.  The default is 3.
.TP
.B max\-age \fIDAYS\fR
The maximum age of the most recent backup before you feel uncomfortable.
The default is 3, meaning that if a volume hasn't been backed up in
the last 3 days it will have red ink in the HTML report.
.TP
.B min\-backups \fICOUNT\fR
The minimum number of backups for each volume to keep on each store,
when pruning.
The default is 1.
.TP
.B prune\-age \fIDAYS\fR
The age at which a backup may be pruned.
The default is 366, meaning a backup will never be pruned until it is
at least a whole year old.
.TP
.B keep\-prune\-logs \fIDAYS\fR
The number of days to keep prune logs for.
The default is 31.
.TP
.B include \fIPATH\fR
Include another file as part of the configuration.
If \fIPATH\fR is a directory then the files within it are included
(excluding dotfiles and backup files).
.SS "Host Directives"
A host stanza is started by a host directive.
It contains other host directives, and one or more volume stanzas.
.TP
.B host \fIHOST\fR
Introduce a host stanza.
The name is used for the backup directory for this host.
.TP
.B hostname \fIHOSTNAME\fR
The SSH hostname for this host.
The default is the name from the host stanza.
.IP
The hostname \fBlocalhost\fR is treated specially: it is assumed to always be
identical to the local system, so files will be read from the local filesystem.
.TP
.B user \fIUSERNAME\fR
The SSH username for this host.
The default is not to supply a username.
.TP
.B always\-up
Indicates that the host is expected to always be available.
If it is not then a warning will be issued when making a backup if it is not.
.PP
In addition, \fBprune\-age\fR, \fBmax\-age\fR and \fBmin\-backups\fR can
be used within a host stanza, and apply to just that host.
.PP
Remote hosts are accessed by SSH.
The user \fBrsbackup\fR runs as must be able to connect to the remote
host (and without a password being entered if it is to be run from a
cron job or similar).
.SS "Volume Directives"
A volume stanza is started by a volume directive.
It contains one or more volume directives.
.TP
.B volume \fIVOLUME PATH\fR
Introduce a volume stanza.
The name is used for the backup directory for this volume.
The path is the absolute path on the host.
.TP
.B exclude \fIPATTERN\fR
An exclusion for this volume.
The pattern is passed to the rsync \fB\-\-exclude\fR option.
This directive may appear multiple times per volume.
.IP
See the rsync man page for full details.
.TP
.B traverse
Traverse mount points.
This suppresses the rsync \fB\-\-one\-file\-system\fR option.
.PP
In addition, \fBprune\-age\fR, \fBmax\-age\fR and \fBmin\-backups\fR can
be used within a volume stanza, and apply to just that volume.
.SH "BACKUP LIFECYCLE"
.SS "Adding A New Host"
To add a new host create a \fBhost\fR entry for it in the configuration file.
.PP
To back up the local host, specify \fBhostname localhost\fR.
Otherwise you can usually omit \fBhostname\fR.
.PP
You may want to set host-wide values for \fBprune\-age\fR,
\fBmax\-age\fR and \fBmin\-backups\fR.
.PP
A host with no volumes has no effect.
.SS "Adding A New Volume"
To add a new volume create a \fBvolume\fR entry for it in the relevant
\fBhost\fR section of the configuration file.
.PP
Add \fBexclude\fR options to skip files you don't want to back up.
This might include temporary files and the contents of "trash"
directories.
.PP
If the volume contains mount points, and you want to back up the
contents of the subsiduary filesystems, then be sure to include the
\fBtraverse\fR option.
.PP
You may want to set per-volume values for \fBprune\-age\fR,
\fBmax\-age\fR and \fBmin\-backups\fR.
.SS "Adding A New Device"
To add a new device, format and mount it and create a
\fIdevice\-id\fR file in its top-level directory.
Add a \fBdevice\fR entry for it in the configuration file and a
\fBstore\fR entry mentioning its usual mount point.
.PP
Under normal circumstances you should make sure that the backup
filesystem is owned by root and mode 0700.
.SS "Making Backups"
To backup up all available volumes to all available devices:
.in +4n
.nf

rsbackup \-\-backup

.fi
.in
You will probably want to automate this.
To only back up a limited set of volumes specify selection arguments
on the command line.
.SS "Pruning Backups"
To prune old backups:
.in +4n
.nf

rsbackup \-\-prune \-\-prune\-incomplete

.fi
.in
You will probably want to automate this.
.PP
An "incomplete backup" occurs when a backup of a volume fails or is
interrupted before completion.
They are not immediately deleted because \fBrsync\fR may be able to
use the files already transferred to save effort on subsequent backups
on the same day, or (if there are no complete backups to use for this
purpose) later days.
.SS "Retiring A Host"
Retiring a host means removing all backups for it.
The suggested approach is to remove configuration for it and then use
\fBrsbackup \-\-retire \fIHOST\fR to remove its backups too.
You can do this the other way around but you will be prompted to check
you really meant to remove backups for a host still listed in the
configuration file.
.PP
If any of the backups for the host are on a retired device you should
retire that device first.
.SS "Retiring A Volume"
Retiring a volume means removing all backups for it.
It is almost the same as retiring a whole host but the command is
\fBrsbackup \-\-retire \fIHOST\fB:\fRVOLUME\fR.
.PP
You can retire multiple hosts and volumes in a single command.
.SS "Retiring A Device"
Retiring a device just means removing the logs for it.
Use \fBrsbackup \-\-retire\-device \fIDEVICE\fR to do this.
The contents of the device are not modified; if you want that you must
do it manually.
.PP
You can retire multiple devices in a single command.
.SH RESTORING
Restore costs extra l-)
.SS "Manual Restore"
The backup has the same layout, permissions etc as the original
system, so it's perfectly possible to simply copy files from a backup
directory to their proper location.
.PP
Be careful to get file ownership right.
The backup is stored with the same numeric user and group ID as the
original system used.
.PP
Until a backup is completed, or while one is being pruned,
a corresponding \fB.incomplete\fR file
will exist.
Check for such a file before restoring any given backup.
.SS "Restoring With rsync"
Supposing that host \fBchymax\fR has a volume called \fBusers\fR in
which user home directories are backed up, and user \fBrjk\fR wants
their entire home directory to be restored, an example restore
command might be:
.in +4n
.nf

rsync \-aSHz \-\-numeric\-ids /store/chymax/users/2010-04-01/rjk/. chymax:~rjk/.

.fi
.in
.PP
You could add the \fB\-\-delete\fR option if you wanted to restore to
exactly the status quo ante, or at the opposite extreme
\fB\-\-existing\fR if you only wanted to restore files that had been
deleted.
.PP
You might prefer to rsync back into a staging area and then pick files
out manually.
.SS "Restoring with tar"
You could tar up a backup directory (or a subset of it) and then untar
it on the target.
Remember to use the \fB\-\-numeric\-owner\fR option to tar.
.SH FILES
.TP
.I /etc/rsbackup/config
Configuration file.
.TP
.I LOGS/YYYY\-MM\-DD\-DEVICE\-HOST\-VOLUME.log
Log file for one attempt to back up a volume.
.TP
.I LOGS/prune\-YYYY\-MM\-DD.log
Log of recently pruning actions.
.TP
.I STORE/HOST/VOLUME/YYYY\-MM\-DD
One backup for a volume.
.TP
.I STORE/HOST/VOLUME/YYYY\-MM\-DD.incomplete
Flag file for an incomplete backup.
.SH "SEE ALSO"
\fBrsbackup.cron\fR(1), \fBrsbackup\-mount\fR(1), \fBrsync\fR(1)
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>

