.TH rsbackup-mount 1
.SH NAME
rsbackup-mount \- mount encrypted disks used by rsbackup
.SH SYNOPSIS
\fBrsbackup-mount\fR [\fIOPTIONS\fR] [\fB--\fR] [\fIDEVICES\fR]
.SH DESCRIPTION
\fBrsbackup-mount\fR mounts and unmounts encrypted partitions used as
backup stores by \fBrsbackup\fR(1).
.SH OPTIONS
=over
.TP
.B --unmount
.TP
.B -u
Unmount devices.
(The default is to mount devices.)
.TP
.B --dry-run
.TP
.B -n
Do nothing, instead print the commands that would be executed.
.TP
.B --help
Display usage message.
.SH CONFIGURATION
Configuration is read from \fI/etc/rsbackup/devices\fR.
This is a shell script fragment.
It should set \fBdevices\fR to a (space-separated) list of device
names and for each device name \fID\fR, define \fID\fR\fB_uuid\fR to
its UUID.
(Have a look in \fI/dev/disk/by-uuid\fR to find device UUIDs).
.SH "SEE ALSO"
\fBrsbackup\fR(1), rsbackup.cron\fR(1)
.SH AUTHOR
Richard Kettlewell <rjk@greenend.org.uk>
