#! /usr/bin/perl -w
use strict;
my $symbol = shift;

(print "char $symbol\[] =\n")
    or die "$!\n";
while(<>) {
    s/[\"\\]/\\$&/g;
    s/\n/\\n/g;
    (print "\"$_\"\n") or die "$!\n";
}
(print ";\n") or die "$!\n";
(close STDOUT) or die "$!\n";
