#! /bin/sh
#
# Copyright (C) 2019 Richard Kettlewell
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
set -e
cd ${srcdir}
status=0
CLANG_FORMAT=/usr/bin/clang-format-7
if ${CLANG_FORMAT} --version >/dev/null 2>&1; then
  :
else
  echo >&2 ${CLANG_FORMAT} failed, skipping check-source test
  exit 77
fi
formatted=$(mktemp -d)
trap "rm -rf ${formatted}" EXIT INT HUP TERM
for path in  *.h *.cc; do
  ${CLANG_FORMAT} ${path} > ${formatted}/${path}
  if diff -u ${path} ${formatted}/${path}; then
    :
  else
    status=1
  fi
  rm -f ${formatted}/${path}
done
exit $status
