char stylesheet[] =
    "/* Copyright © 2011 Richard Kettlewell.\n"
    " *\n"
    " * This program is free software: you can redistribute it and/or modify\n"
    " * it under the terms of the GNU General Public License as published by\n"
    " * the Free Software Foundation, either version 3 of the License, or\n"
    " * (at your option) any later version.\n"
    " *\n"
    " * This program is distributed in the hope that it will be useful,\n"
    " * but WITHOUT ANY WARRANTY; without even the implied warranty of\n"
    " * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the\n"
    " * GNU General Public License for more details.\n"
    " *\n"
    " * You should have received a copy of the GNU General Public License\n"
    " * along with this program.  If not, see http://www.gnu.org/licenses/.\n"
    " */\n"
    "body {\n"
    "  color: black;\n"
    "  background-color: white\n"
    "}\n"
    "\n"
    "a:link, a:visited, a:active {\n"
    "  color: blue;\n"
    "  text-decoration: underline\n"
    "}\n"
    "\n"
    "h1 {\n"
    "  background-color: #e0ffe0;\n"
    "  padding: 0.2em\n"
    "}\n"
    "\n"
    "h2 {\n"
    "  background-color: #e0e0e0;\n"
    "  padding: 0.2em\n"
    "}\n"
    "\n"
    "h3 {\n"
    "  text-decoration: underline\n"
    "}\n"
    "\n"
    "a.h3 {\n"
    "  margin-left: 1em\n"
    "}\n"
    "\n"
    "h1,h2,h3,h4 {\n"
    "  font-family: sans-serif\n"
    "}\n"
    "\n"
    "table {\n"
    "  border-collapse: collapse\n"
    "}\n"
    "\n"
    "th {\n"
    "  background-color: #e0e0e0;\n"
    "  border-left: 1px solid #e0e0e0;\n"
    "  border-top: 1px solid #e0e0e0;\n"
    "  border-right: 1px solid #e0e0e0\n"
    "}\n"
    "\n"
    "td {\n"
    "  border: 1px solid black;\n"
    "  vertical-align: top;\n"
    "  padding-left: 4px;\n"
    "  padding-right: 4px\n"
    "}\n"
    "\n"
    "td.bad {\n"
    "  background-color: #ff4040;\n"
    "  color: #ffffff\n"
    "}\n"
    "\n"
    "td.good {\n"
    "  background-color: #e0ffe0;\n"
    "  color: #000000\n"
    "}\n"
    "\n"
    "span.bad {\n"
    "  color: #ff4040\n"
    "}\n"
    "\n"
    "pre.log {\n"
    "  background-color: #f0f0f0\n"
    "}\n"
    "\n"
    ".example {\n"
    "  border-left: 2px solid black;\n"
    "  padding-left: 2px\n"
    "}\n"
    "\n"
    "div.volume {\n"
    "  margin-left: 1em\n"
    "}\n"
    "\n"
    ".recent {\n"
    "  color: #ff4040\n"
    "}\n"
    "\n"
    "img.history {\n"
    "  border: 1px solid black;\n"
    "  padding: 2px\n"
    "}\n";
