char stylesheet[] =
"body {\n"
"  color: black;\n"
"  background-color: white\n"
"}\n"
"\n"
"a:link, a:visited, a:active {\n"
"  color: blue;\n"
"  text-decoration: underline\n"
"}\n"
"\n"
"h1 {\n"
"  background-color: #e0ffe0\n"
"}\n"
"\n"
"h2 {\n"
"  background-color: #e0e0e0\n"
"}\n"
"\n"
"h3 {\n"
"  text-decoration: underline\n"
"}\n"
"\n"
"h1,h2,h3,h4 {\n"
"  font-family: sans-serif\n"
"}\n"
"\n"
"table {\n"
"  border-collapse: collapse\n"
"}\n"
"\n"
"th {\n"
"  background-color: #e0e0e0;\n"
"  border-left: 1px solid #e0e0e0;\n"
"  border-top: 1px solid #e0e0e0;\n"
"  border-right: 1px solid #e0e0e0\n"
"}\n"
"\n"
"td {\n"
"  border: 1px solid black;\n"
"  vertical-align: top;\n"
"  padding-left: 4px;\n"
"  padding-right: 4px\n"
"}\n"
"\n"
"td.bad {\n"
"  background-color: #ff4040;\n"
"  color: #ffffff\n"
"}\n"
"\n"
"td.good {\n"
"  background-color: #e0ffe0;\n"
"  color: #000000\n"
"}\n"
"\n"
"span.bad {\n"
"  color: #ff4040\n"
"}\n"
"\n"
"pre.log {\n"
"  background-color: #f0f0f0\n"
"}\n"
"\n"
"div.volume {\n"
"  margin-left: 1em\n"
"}\n"
;
