#!/bin/sh
set -e
set -x
#export HOMEBREW_NO_AUTO_UPDATE=yes # transient acceleration
brew unlink python@2 # workaround clash with python3 (which seems to be a pangomm dep)
brew install pangomm cairomm libsigc++ clang-format
brew link libsigc++
brew link cairomm

pkg-config --cflags cairomm-1.0 || true
pkg-config --cflags pangomm-1.4 || true
